export const productsMock = [
  {
    __typename: 'Product',
    id: 'EP3678-CUSA14807_00-JUMANJIBASEGAME0',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/cfn/11307lxXmX1CynrUl-tYBZPDfUVtx_zUwqIEyY1r6tIwDXm0zN4wNhuPbF7ad8Qi6y0-kxPnOOIotbLxOlbOVo0_BG4qEOjf.png',
    },
    name: 'JUMANJI: The Video Game',
    npTitleId: 'CUSA14807_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 39.99,
      discountText: '-100%',
      discountedPrice: null,
      isExclusive: true,
      isFree: true,
      isTiedToSubscription: true,
      serviceBranding: ['PS_PLUS'],
      upsellServiceBranding: ['PS_PLUS'],
      upsellText: 'Extra',
      discountPercentage: 100,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-CUSA15090_00-NEEDFORSPEED2020',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202210/3121/Xz6kd2CORZxe8JnfNJwvA35A.png',
    },
    name: 'Need for Speed™ Heat',
    npTitleId: 'CUSA15090_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-90%',
      discountedPrice: 6.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['EA_ACCESS'],
      upsellText: 'Included',
      discountPercentage: 90,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-CUSA23265_00-NEEDFORSPEEDHPR0',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202210/3122/AooxHg4WoMdhe8oPQYn3XdrG.png',
    },
    name: 'Need for Speed™ Hot Pursuit Remastered',
    npTitleId: 'CUSA23265_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 39.99,
      discountText: '-90%',
      discountedPrice: 3.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['EA_ACCESS'],
      upsellText: 'Included',
      discountPercentage: 90,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP2032-CUSA02453_00-SG2NDENCORE00000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/rnd/202106/2922/sJoLxB744RhScTor36FPLnCd.png',
    },
    name: 'Skullgirls 2nd Encore',
    npTitleId: 'CUSA02453_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 24.99,
      discountText: '-90%',
      discountedPrice: 2.49,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 90,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0700-CUSA14054_00-OPWSDLXED0000000',
    localizedStoreDisplayClassification: 'Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP0700/CUSA14054_00/UdqjEdAZ5LzDDYsL9GXAn89H9YrOgOGN.png',
    },
    name: 'ONE PIECE World Seeker Deluxe Edition',
    npTitleId: 'CUSA14054_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 97.99,
      discountText: '-90%',
      discountedPrice: 9.79,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 90,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-PPSA02199_00-JEDIFO1DELUXEEDN',
    localizedStoreDisplayClassification: 'Game Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202105/2621/IYejmyize0uwfFEhzbSIO5r0.png',
    },
    name: 'STAR WARS Jedi: Fallen Order™ Deluxe Edition',
    npTitleId: 'PPSA02199_00',
    platforms: ['PS4', 'PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 59.99,
      discountText: '-85%',
      discountedPrice: 8.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1001-PPSA01463_00-0000000OAKNGSIEE',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202010/2323/p50N4PBK9rNanGYKFecTvac5.png',
    },
    name: 'Borderlands 3 PS4™ &  PS5™',
    npTitleId: 'PPSA01463_00',
    platforms: ['PS4', 'PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-85%',
      discountedPrice: 10.49,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1018-CUSA05459_00-SEASONPASS000000',
    localizedStoreDisplayClassification: 'Add-On Pack',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP1018/CUSA05459_00/9rDOGEXmNrXGvSCqBmghzsYnGxWsa2cm.png',
    },
    name: 'Injustice™ 2 Ultimate Pack',
    npTitleId: 'CUSA05459_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 39.99,
      discountText: '-85%',
      discountedPrice: 5.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0700-CUSA06014_00-ORIGINALS0000000',
    localizedStoreDisplayClassification: 'Game Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202111/0907/CoiLZPzBYqZ7vUGlfCcUVWB0.png',
    },
    name: 'TEKKEN 7 - Originals Edition',
    npTitleId: 'CUSA06014_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 99.99,
      discountText: '-85%',
      discountedPrice: 14.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-CUSA15089_00-STARWARSQUADRONS',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/rnd/202009/2410/aaIGMZl7LGnfbmQNOrHOrL6c.png',
    },
    name: 'STAR WARS™: Squadrons',
    npTitleId: 'CUSA15089_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 39.99,
      discountText: '-85%',
      discountedPrice: 5.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['EA_ACCESS'],
      upsellText: 'Included',
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0700-CUSA08992_00-DBFDELUXE0000000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP0700/CUSA08992_00/A0PjAX6idUGDcfq98WenOvPONMa9nZ8g.png',
    },
    name: 'DRAGON BALL FIGHTERZ - FighterZ Edition',
    npTitleId: 'CUSA08992_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 99.99,
      discountText: '-85%',
      discountedPrice: 14.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-CUSA10852_00-PVZGW3BASEGAME00',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/rnd/202008/3107/m04V1Wbq0ag6IAp3UozdjSCh.png',
    },
    name: 'Plants vs. Zombies: Battle for Neighborville™',
    npTitleId: 'CUSA10852_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 29.99,
      discountText: '-85%',
      discountedPrice: 4.49,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['EA_ACCESS'],
      upsellText: 'Included',
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0700-CUSA17226_00-OPPW4EUHDDGAME00',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/cfn/11307ZeyIJ-CNDOZaMijl0UcNihbdRUTuE7agy3ANCO38VewX7XgP038qyqJCPQ3qNuehqVUIjN-qFBD6qOVpEIv9Jk6l0j9.png',
    },
    name: 'ONE PIECE: PIRATE WARRIORS 4',
    npTitleId: 'CUSA17226_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-85%',
      discountedPrice: 10.49,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP3969-CUSA12414_00-HITMANSTANDARD00',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP3969/CUSA12414_00/WtCILzY5fNhooQt2qUTcFYD7aROhupmo.png',
    },
    name: 'HITMAN™ 2',
    npTitleId: 'CUSA12414_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-85%',
      discountedPrice: 10.49,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1018-CUSA02152_00-SHADOWMORDORGOTY',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP1018/CUSA02152_00/Aj500YroQRj4l755pgq7CbBWxkjL9RlQ.png',
    },
    name: 'Middle-earth™: Shadow of Mordor™-Game of the Year Edition',
    npTitleId: 'CUSA02152_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 59.99,
      discountText: '-85%',
      discountedPrice: 8.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1018-CUSA09897_00-SHOWTIME00000000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP1018/CUSA09897_00/ZrELiHpQ22q4bTKjOrqvA1iCxjZk7ndg.png',
    },
    name: 'LEGO® The Incredibles',
    npTitleId: 'CUSA09897_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 59.99,
      discountText: '-85%',
      discountedPrice: 8.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 85,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1018-CUSA07744_00-LEGONINJAGOMOVIE',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP1018/CUSA07744_00/dohPi73uhfvsRsS9A7VJ1yH8y5Ep1kew.png',
    },
    name: 'LEGO® NINJAGO® Movie Video Game',
    npTitleId: 'CUSA07744_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 59.99,
      discountText: '-84%',
      discountedPrice: 9.59,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 84,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-CUSA14209_00-DELUXEEDITION000',
    localizedStoreDisplayClassification: 'Game Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202212/0609/o24vomH8g8If1lggjQOzf0PF.png',
    },
    name: 'UFC® 4 Deluxe Edition',
    npTitleId: 'CUSA14209_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 79.99,
      discountText: '-80%',
      discountedPrice: 15.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0001-CUSA08609_00-TC2GOLD200000000',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202106/1607/BfevxYujMvsVNJaY0SZJM0cq.png',
    },
    name: 'The Crew 2 Gold Edition',
    npTitleId: 'CUSA08609_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 89.99,
      discountText: '-80%',
      discountedPrice: 17.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-CUSA08004_00-AWAYOUTEU0000000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP0006/CUSA08004_00/uYjNSTuC1lpCeOLL7M6Gye9tUH28W8F3.png',
    },
    name: 'A Way Out',
    npTitleId: 'CUSA08004_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 29.99,
      discountText: '-80%',
      discountedPrice: 5.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['EA_ACCESS'],
      upsellText: 'Included',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP3930-CUSA15249_00-4283678837524043',
    localizedStoreDisplayClassification: 'Game Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/rnd/202111/2402/b4Es7ltfcu1U8tCowxQEUpLT.png',
    },
    name: 'Black Desert: Traveler Edition',
    npTitleId: 'CUSA15249_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 29.99,
      discountText: '-80%',
      discountedPrice: 5.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-CUSA25503_00-HWUNLEASHEDFGAME',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202102/1008/rS6hKW6RluVColmbTAIt9Fl1.png',
    },
    name: 'HOT WHEELS UNLEASHED™',
    npTitleId: 'CUSA25503_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 49.99,
      discountText: '-80%',
      discountedPrice: 9.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['PS_PLUS'],
      upsellText: 'Premium',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-PPSA02325_00-HWUNLEASHEDFGAME',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202102/1008/rS6hKW6RluVColmbTAIt9Fl1.png',
    },
    name: 'HOT WHEELS UNLEASHED™',
    npTitleId: 'PPSA02325_00',
    platforms: ['PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 49.99,
      discountText: '-80%',
      discountedPrice: 9.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['PS_PLUS'],
      upsellText: 'Premium',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-CUSA25503_00-HWUGAMEOFTHEYEAR',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1114/m8ByWIwEOS0LGLkBWZyoOBah.png',
    },
    name: 'HOT WHEELS UNLEASHED™ - Game of the Year Edition',
    npTitleId: 'CUSA25503_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 89.99,
      discountText: '-80%',
      discountedPrice: 17.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-PPSA02325_00-HWUGAMEOFTHEYEAR',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1114/m8ByWIwEOS0LGLkBWZyoOBah.png',
    },
    name: 'HOT WHEELS UNLEASHED™ - Game of the Year Edition',
    npTitleId: 'PPSA02325_00',
    platforms: ['PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 89.99,
      discountText: '-80%',
      discountedPrice: 17.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1001-CUSA15381_00-CIV6BASE00000000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/cfn/11307KFcs3gBlcheONy-ZOYZ5kplFnq5jXinUSI8HkCc8P2gdI1_32JrKJ-vxns32LjXBcQteG2EOwuzWS_KXqE5VCYFmS4Z.png',
    },
    name: 'Sid Meier’s Civilization VI',
    npTitleId: 'CUSA15381_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 29.99,
      discountText: '-80%',
      discountedPrice: 5.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP2134-CUSA12894_00-0225830765462589',
    localizedStoreDisplayClassification: 'Weapons',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202109/2714/LLIOTVKIG8coRSGpl55UGXPG.png',
    },
    name: 'Warface - Heist Edition',
    npTitleId: 'CUSA12894_00',
    platforms: [],
    price: {
      __typename: 'SkuPrice',
      basePrice: 4.99,
      discountText: '-80%',
      discountedPrice: 0.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1018-CUSA03679_00-MORTALKOMBATXL00',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP1018/CUSA03679_00/WkptPw8MeeOqu2kskd6DNquGoYjKFc46.png',
    },
    name: 'Mortal Kombat XL',
    npTitleId: 'CUSA03679_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 49.99,
      discountText: '-80%',
      discountedPrice: 9.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0700-CUSA07202_00-ACE7TOPGUNME2022',
    localizedStoreDisplayClassification: 'Game Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202205/1013/05QuyU4xam0lTwGB4r7JMT7V.png',
    },
    name: 'ACE COMBAT™ 7: SKIES UNKNOWN - TOP GUN: Maverick Edition',
    npTitleId: 'CUSA07202_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 84.99,
      discountText: '-80%',
      discountedPrice: 16.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-PPSA01599_00-RIDE4FULLGAME000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202007/1712/WBU8MtDHSutQ5o9FxXm4Fpwp.png',
    },
    name: 'RIDE 4',
    npTitleId: 'PPSA01599_00',
    platforms: ['PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-80%',
      discountedPrice: 13.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-CUSA18194_00-RIDE4FULLGAME000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202007/1712/WBU8MtDHSutQ5o9FxXm4Fpwp.png',
    },
    name: 'RIDE 4',
    npTitleId: 'CUSA18194_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-80%',
      discountedPrice: 13.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-PPSA01599_00-RIDE4SPECEDITION',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202007/1714/KYxcWznrfdx0cC4IVR2PtbeA.png',
    },
    name: 'RIDE 4 - Special Edition',
    npTitleId: 'PPSA01599_00',
    platforms: ['PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 99.99,
      discountText: '-80%',
      discountedPrice: 19.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4356-CUSA18194_00-RIDE4SPECEDITION',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202007/1714/KYxcWznrfdx0cC4IVR2PtbeA.png',
    },
    name: 'RIDE 4 - Special Edition',
    npTitleId: 'CUSA18194_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 99.99,
      discountText: '-80%',
      discountedPrice: 19.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0082-PPSA01632_00-2723562273397353',
    localizedStoreDisplayClassification: 'Item',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202105/2715/tl3DIlOzk99I5cQulAE7RRpS.png',
    },
    name: "Marvel's Avengers Kate Bishop Heroic Starter Pack - PS5",
    npTitleId: 'PPSA01632_00',
    platforms: ['PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 4.99,
      discountText: '-80%',
      discountedPrice: 0.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0082-CUSA14030_00-9789799560447506',
    localizedStoreDisplayClassification: 'Item',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202105/2715/tl3DIlOzk99I5cQulAE7RRpS.png',
    },
    name: "Marvel's Avengers Kate Bishop Heroic Starter Pack - PS4",
    npTitleId: 'CUSA14030_00',
    platforms: [],
    price: {
      __typename: 'SkuPrice',
      basePrice: 4.99,
      discountText: '-80%',
      discountedPrice: 0.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0082-PPSA01632_00-3156481590490967',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/rnd/202111/1814/26mVmWE2zXaIyBVGN0Gwkh1s.png',
    },
    name: "Marvel's Avengers",
    npTitleId: 'PPSA01632_00',
    platforms: ['PS4', 'PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 49.99,
      discountText: '-80%',
      discountedPrice: 9.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['PS_PLUS'],
      upsellText: 'Extra',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0082-PPSA01632_00-7094297436334871',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/rnd/202111/1814/jDB8qgvekka1q4QHf7diT5Fi.png',
    },
    name: "Marvel's Avengers: Exclusive Digital Edition",
    npTitleId: 'PPSA01632_00',
    platforms: ['PS4', 'PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 59.99,
      discountText: '-80%',
      discountedPrice: 11.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4040-CUSA11487_00-ASSETTOCORSASPEC',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP4040/CUSA11487_00/iRqD2BxH4DihRaCQYSK3Q5JUzaNtBU19.png',
    },
    name: 'Assetto Corsa Ultimate Edition',
    npTitleId: 'CUSA11487_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 39.99,
      discountText: '-80%',
      discountedPrice: 7.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['PS_PLUS'],
      upsellText: 'Save 5% more',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0006-CUSA10416_00-COLDWOODPIKE0000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP0006/CUSA10416_00/7OtAlABbzptPIcDGDueFSbuTT8OSaVZk.png',
    },
    name: 'Unravel Two',
    npTitleId: 'CUSA10416_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 19.99,
      discountText: '-80%',
      discountedPrice: 3.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['EA_ACCESS'],
      upsellText: 'Included',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0001-CUSA14390_00-TGTDLXEDITION000',
    localizedStoreDisplayClassification: 'Game Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202109/0712/PBl8MRpxqYhzALKQe2sfOFp7.png',
    },
    name: "Tom Clancy's Ghost Recon® Breakpoint Deluxe Edition",
    npTitleId: 'CUSA14390_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 79.99,
      discountText: '-80%',
      discountedPrice: 15.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4122-CUSA13645_00-VERMINTIDE2000EU',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP4122/CUSA13645_00/kQoHA5x2wEx7ruWi2lNhKyTXo4oEfOAP.png',
    },
    name: 'Warhammer: Vermintide 2',
    npTitleId: 'CUSA13645_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 29.99,
      discountText: '-80%',
      discountedPrice: 5.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['PS_PLUS'],
      upsellText: 'Extra',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4122-CUSA13645_00-V2ULTIMATEBUNDEU',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP4122/CUSA13645_00/WeIyHJa9YnlYAQTVU2V5GLSClA9bylrv.png',
    },
    name: 'Warhammer: Vermintide 2 - Ultimate Edition',
    npTitleId: 'CUSA13645_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 54.99,
      discountText: '-80%',
      discountedPrice: 10.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP0001-CUSA02819_00-GRWULTIMBUNDLE00',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP0001/CUSA02819_00/TPIim69BcYaSyEQlrh2rsMsMgkGGhBk8.png',
    },
    name: 'Tom Clancy’s Ghost Recon® Wildlands Ultimate Edition',
    npTitleId: 'CUSA02819_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 99.99,
      discountText: '-80%',
      discountedPrice: 19.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1018-CUSA08476_00-LEGOMARVELSH2001',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/rnd/202110/2623/1xTLlGpMSRci1IGLUlS1dFbc.png',
    },
    name: 'LEGO® Marvel Super Heroes 2',
    npTitleId: 'CUSA08476_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 59.99,
      discountText: '-80%',
      discountedPrice: 11.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4064-CUSA04022_00-WORMSDCBN0000000',
    localizedStoreDisplayClassification: 'Game Bundle',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/img/cfn/11307b9J4namTSFLRyRb0V7OnCFZU4IjyJEkjYY8OQt1RM4gifisOjIQeIiqrHtd7qva0Ev1dAf6LF7uDmxuHiYOB3IFQ2Qz.png',
    },
    name: 'Worms Battlegrounds + Worms W.M.D',
    npTitleId: 'CUSA04022_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 34.99,
      discountText: '-80%',
      discountedPrice: 6.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4064-CUSA04022_00-WORMSWMD00000000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP4064/CUSA04022_00/DAyywhQEMaRv3o98rrEE0eyIpfJo5ixg.png',
    },
    name: 'Worms W.M.D',
    npTitleId: 'CUSA04022_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 29.99,
      discountText: '-80%',
      discountedPrice: 5.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['PS_PLUS'],
      upsellText: 'Extra',
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4062-CUSA15436_00-KCDROYALEDITION0',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP4062/CUSA15436_00/hV9fGwOQuuNCuVywqRIEvqn5SXxoA0Dy.png',
    },
    name: 'Kingdom Come: Deliverance Royal Edition',
    npTitleId: 'CUSA15436_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 39.99,
      discountText: '-80%',
      discountedPrice: 7.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4008-CUSA18653_00-7317235466429033',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202006/1514/C6jValrFcqhj3sGZi54BL7VG.png',
    },
    name: 'Hunting Simulator 2 Bear Hunter Edition',
    npTitleId: 'CUSA18653_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-80%',
      discountedPrice: 13.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP4008-PPSA01899_00-7566551321582931',
    localizedStoreDisplayClassification: 'Premium Edition',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/vulcan/ap/rnd/202006/1514/C6jValrFcqhj3sGZi54BL7VG.png',
    },
    name: 'Hunting Simulator 2 Bear Hunter Edition',
    npTitleId: 'PPSA01899_00',
    platforms: ['PS5'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 69.99,
      discountText: '-80%',
      discountedPrice: 13.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
  {
    __typename: 'Product',
    id: 'EP1018-CUSA00044_00-LEGOMARVEL000000',
    localizedStoreDisplayClassification: 'Full Game',
    media: {
      __typename: 'Media',
      role: 'MASTER',
      type: 'IMAGE',
      url: 'https://image.api.playstation.com/cdn/EP1018/CUSA00044_00/irxvPqAamKVsJ28xuUyc6g21rDaXJLCi.png',
    },
    name: 'LEGO® Marvel™ Super Heroes',
    npTitleId: 'CUSA00044_00',
    platforms: ['PS4'],
    price: {
      __typename: 'SkuPrice',
      basePrice: 39.99,
      discountText: '-80%',
      discountedPrice: 7.99,
      isExclusive: false,
      isFree: false,
      isTiedToSubscription: false,
      serviceBranding: ['NONE'],
      upsellServiceBranding: ['NONE'],
      upsellText: null,
      discountPercentage: 80,
    },
    skus: [
      {
        __typename: 'Sku',
        type: 'STANDARD',
      },
    ],
  },
]
